### PR TITLE
Fix: Comment escaping with multiple `#`

### LINKED ISSUE #30: Comment escaping with `##` should not apply to lines that begin with `#`
After upgrading to Hyprland 0.36.0 I had dozens of configuration errors in the error popup. The issue ended up being that I was using `##` to prefix section titles in my config to distinguish them from regular commented lines and to make the config easier to search. The changelog for 0.36.0 mentions:

> `##` is now properly treated as an escaped `#`.

but I feel this should be ignored for lines where the first character is `#` since it seems unexpected, but perhaps there's a scenario where a config line could begin with a literal `#` that I'm not aware of.

### PR DESCRIPTION
**Pull request by Micovec**
This PR fixes #30 

Meaning that this:

```
  	  	##### This is a comment with leading spaces and tabs
```

is now a valid config comment and the whole line (in this case) would be ignored.

### CODE REVIEW

File: src/config.cpp [hunk 1]
```diff
@@ -483,12 +504,14 @@ CParseResult CConfig::parseVariable(const std::string& lhs, const std::string& r
...
-    size_t       lastHashPos = 0;
+    line = removeBeginSpacesTabs(line);
+
+    auto   commentPos  = line.find('#');
+    size_t lastHashPos = 0;
 
     while (commentPos != std::string::npos) {
         bool escaped = false;
-        if (commentPos < line.length() - 1) {
+        if (commentPos < line.length() - 1 && commentPos != 0) {
```
Comment (vaxerski) [inline src/config.cpp:514]: what's the point of everything but this

Comment (Micovec) [reply src/config.cpp:514]: Line 507 removes leading spaces and tabs so when you hit `#` it is understood as a comment because it can't be keyword, value or section

Comment (Micovec) [reply src/config.cpp:514]: And I thought that the best way for checking if `##` is a start of a comment is to check for first non-space, non-tab character since there is no reason for not having spaces and tabs before the actual comment.

```
    ## Why not allow this for a comment for example
```

Without the other stuff parser would grab `##`, escape it (because `commentPos` won't be 0 in this case) and then tried to parse it as a key, value which would resolve in an error.

Comment (vaxerski) [reply src/config.cpp:514]: my question is why the new functions.

Comment (Micovec) [reply src/config.cpp:514]: For better readability I guess, the functionality might be needed in the future and also I thought that removing any spaces and tabs at the end should be done after the comment is removed because if there are any spaces at the end of the _line_ they are part of the actual comment and get removed nevertheless.

They aren't necessary... should I remove them and replace calling them with just `removeBeginEndSpacesTabs`?

Comment (Micovec) [reply src/config.cpp:493]: Done

File: src/config.cpp [hunk 2]
```diff
@@ -483,12 +483,14 @@ CParseResult CConfig::parseVariable(const std::string& lhs, const std::string& r
...
-    size_t       lastHashPos = 0;
+    line = removeBeginEndSpacesTabs(line);
+
+    auto   commentPos  = line.find('#');
+    size_t lastHashPos = 0;
 
     while (commentPos != std::string::npos) {
         bool escaped = false;
-        if (commentPos < line.length() - 1) {
+        if (commentPos < line.length() - 1 && commentPos != 0) {
```
Comment (vaxerski) [inline src/config.cpp:493]: also why not just 
```cpp
if (commentPos == 0)
    return;
```

above the while loop? If commentPos is 0, the line is useless

Comment (Micovec) [reply src/config.cpp:493]: Agree. I never know to which extend I should create PRs. It would also make sense to add

```cpp
if (line.empty())
    return;
```

just below the second space removal because at that time the line is useless aswell. And then remove all `line.empty()` conditions afterwards.

And other thing (probably another PR) is that the parser should probably ignore all whitespaces, not just space and tab, with [std::isspace](https://en.cppreference.com/w/cpp/string/byte/isspace).

Comment (Micovec) [reply src/config.cpp]: Done

**Review by vaxerski — APPROVED** [review]
lgtm
